"""Bake NA-East prices for the Hell-key reward items into prices.js.

Prices come from the shared market bake (/market/prices.json, written by
tools/bake-market.py earlier in the same refresh run); run on its own, or when
that bake did not land this run, it fetches the loa-buddy feed directly. Either
way the robust price is tools/marketlib.py's: drop today, trim 2 high/low,
recency-weighted mean (decay 0.9), falling back to spot.

Never bakes a bad number: if the feed fails, or any item comes back without a
positive price, prices.js is left untouched and the script exits 1.

    python fetch_prices.py            # shared bake if fresh, else the feed
    python fetch_prices.py --live     # always the feed
"""
import datetime, json, pathlib, sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "tools"))
import marketlib  # noqa: E402

SLUGS = [
 "superior-abidos-fusion-material","great-destiny-leapstone",
 "destiny-crystallized-destruction-stone","destiny-crystallized-guardian-stone",
 "destiny-shard-pouch-l","destiny-shard-pouch-m","destiny-shard-pouch-s",
 "lavas-breath","glaciers-breath","abidos-fusion-material","destiny-leapstone",
 "destiny-destruction-stone","destiny-guardian-stone"]
REGION = "nae"
# baked per unit where the feed prices a 100-stack (crystallized stones) or a pouch
# (shards: L = 3000; S=1000, M=2000 per the codex)
PER_UNIT = {"destiny-crystallized-destruction-stone": 100, "destiny-crystallized-guardian-stone": 100,
            "destiny-shard-pouch-l": 3000}
OUT = HERE / "prices.js"


def main(argv):
    try:
        market = marketlib.get_market(SLUGS, (REGION,), live="--live" in argv)
        items = market["regions"][REGION]["items"]
    except Exception as e:
        sys.exit(f"market feed failed ({e}) — not baking; prices.js left as it was.")
    raw, baked, bad = {}, {}, []
    for s in SLUGS:
        it = items.get(s) or {}
        price = it.get("robust") or it.get("spot")
        raw[s] = {"spot": it.get("spot"), "robust": it.get("robust"),
                  "hist": [p for _, p in it.get("history", [])]}
        print(f"{s:42s} spot={it.get('spot')!s:>10} robust={it.get('robust')!s:>10} days={len(raw[s]['hist'])}")
        if not price or price <= 0:
            bad.append(s)
            continue
        baked[s] = round(price / PER_UNIT.get(s, 1), 3)
    if bad:
        sys.exit(f"no price for {len(bad)} item(s): {', '.join(bad)} — not baking; prices.js left as it was.")
    (HERE / "prices_raw.json").write_text(json.dumps(raw, indent=1), encoding="utf-8")
    day = str(datetime.date.today())
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by fetch_prices.py (NA East, robust 14-day price); do not hand-edit\n")
        f.write("const PRICES=" + json.dumps({"date": day, "region": REGION, "perUnit": baked}) + ";\n")
    print("wrote prices.js")


if __name__ == "__main__":
    main(sys.argv[1:])
