"""Fetch NA-East prices for the Hell-key reward items (loa-buddy feed) and
compute the robust price per loa-market-data: drop today, trim 2 high/low,
recency-weighted mean (decay 0.9)."""
import json, sys, urllib.request, datetime
API = "https://marketdata-api.yrzhao1068589.workers.dev/v1/prices"
UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)", "Content-Type": "application/json"}
SLUGS = sys.argv[1:] or [
 "superior-abidos-fusion-material","great-destiny-leapstone",
 "destiny-crystallized-destruction-stone","destiny-crystallized-guardian-stone",
 "destiny-shard-pouch-l","destiny-shard-pouch-m","destiny-shard-pouch-s",
 "lavas-breath","glaciers-breath","abidos-fusion-material","destiny-leapstone",
 "destiny-destruction-stone","destiny-guardian-stone"]
def post(path, body):
    r = urllib.request.Request(API+path, data=json.dumps(body).encode(), headers=UA)
    return json.load(urllib.request.urlopen(r, timeout=30))
def get(path):
    r = urllib.request.Request(API+path, headers=UA)
    return json.load(urllib.request.urlopen(r, timeout=30))
latest = {x["item_slug"]: x for x in post("/latest", {"region_slug":"nae","item_slugs":SLUGS})}
end = datetime.date.today(); start = end - datetime.timedelta(days=15)
out = {}
for s in SLUGS:
    try:
        h = get(f"/historical/nae/{s}?start_date={start}&end_date={end}")
    except Exception as e:
        print(s, "hist error", e); h = []
    avgs = [d["avg_price"] for d in sorted(h, key=lambda d: d["day"], reverse=True)]
    comp = avgs[1:]                      # drop the live day
    robust = None
    if len(comp) >= 5:
        srt = sorted(comp); keep = [v for v in comp if v not in srt[:2]+srt[-2:]] or comp
        w = [0.9**i for i in range(len(keep))]
        robust = sum(v*wi for v, wi in zip(keep, w)) / sum(w)
    out[s] = {"spot": latest.get(s, {}).get("price"), "ts": latest.get(s, {}).get("timestamp"),
              "hist": avgs, "robust": robust}
    print(f"{s:42s} spot={out[s]['spot']!s:>10} robust={robust and round(robust,2)!s:>10} days={len(avgs)}")
json.dump(out, open("prices_raw.json","w"), indent=1)
# baked defaults for the page: robust price (fallback spot), per unit where the
# feed prices a 100-stack (crystallized stones) or a pouch (shards: L = 3000; S=1000, M=2000 per the codex)
PER_UNIT = {"destiny-crystallized-destruction-stone": 100, "destiny-crystallized-guardian-stone": 100,
            "destiny-shard-pouch-l": 3000}
baked = {s: round((v["robust"] or v["spot"] or 0) / PER_UNIT.get(s, 1), 3) for s, v in out.items()}
with open("prices.js", "w") as f:
    f.write("// generated by fetch_prices.py (NA East, robust 14-day price); do not hand-edit" + chr(10))
    f.write("const PRICES=" + json.dumps({"date": str(end), "region": "nae", "perUnit": baked}) + ";" + chr(10))
print("wrote prices.js")
