// Regenerate icons.js from the astrogem-calculator class icon set.
// Usage: node tools/gen-icons.js [path-to-class-icons-dir]
const fs = require('fs');
const path = require('path');

const SRC = process.argv[2] || 'C:/Users/Shizu/astrogem-calculator/assets/class-icons';
const OUT = path.join(__dirname, '..', 'icons.js');

// Bard and Artist are excluded from the rankings and never rendered.
const SKIP = new Set(['Bard', 'Artist']);

const entries = fs.readdirSync(SRC)
  .filter(f => f.endsWith('.svg'))
  .map(f => path.basename(f, '.svg'))
  .filter(name => !SKIP.has(name))
  .sort()
  .map(name => {
    let svg = fs.readFileSync(path.join(SRC, name + '.svg'), 'utf8').trim();
    svg = svg.replace(/\s(width|height)="[^"]*"/g, '');
    svg = svg.replace('<svg ', '<svg aria-hidden="true" ');
    return `  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`;
  });

fs.writeFileSync(OUT,
  '// Generated by tools/gen-icons.js — single-color class glyphs (fill: currentColor)\n' +
  '// from github.com/shizukaziye/astrogem-calculator. Do not edit by hand.\n' +
  'window.CLASS_ICONS = {\n' + entries.join('\n') + '\n};\n');
console.log('wrote', OUT, entries.length, 'icons,', (fs.statSync(OUT).size / 1024).toFixed(0) + 'KB');
