// generated by fetch_prices.py (NA East, robust 14-day price, gold per ONE unit); do not hand-edit
window.GPD_PRICES={"date": "2026-10-01", "region": "nae", "perUnit": {"superior-abidos-fusion-material": 137.08, "destiny-crystallized-destruction-stone": 29.318, "destiny-crystallized-guardian-stone": 3.02, "great-destiny-leapstone": 56.85, "lavas-breath": 465.85, "glaciers-breath": 439.56}};
