// generated by fetch_prices.py (NA East, robust 14-day price, gold per ONE unit); do not hand-edit
window.GPD_PRICES={"date": "2026-09-28", "region": "nae", "perUnit": {"superior-abidos-fusion-material": 138.58, "destiny-crystallized-destruction-stone": 29.239, "destiny-crystallized-guardian-stone": 2.962, "great-destiny-leapstone": 57.38, "lavas-breath": 472.21, "glaciers-breath": 436.86}};
