// generated by fetch_prices.py (NA East, robust 14-day price, gold per ONE unit); do not hand-edit
window.GPD_PRICES={"date": "2026-09-26", "region": "nae", "perUnit": {"superior-abidos-fusion-material": 143.14, "destiny-crystallized-destruction-stone": 28.99, "destiny-crystallized-guardian-stone": 2.835, "great-destiny-leapstone": 58.95, "lavas-breath": 473.36, "glaciers-breath": 429.11}};
