"""Turn the reward-picker __DATA__ dump (hell_s4_data/picker_data.json) into
data/rewards.json + data.js for the calculator. Run after refreshing the dump."""
import json, os, re
SRC = os.path.expanduser("~/hell_s4_data/picker_data.json")
d = json.load(open(SRC, encoding="utf-8"))
WANT = {  # picker label -> our key id
    "1730 Splendid Hell Key": "hell1730",
    "1750 Hell Key": "hell1750",
    "1730 Splendid Netherworld Key": "nw1730",
    "1750 Netherworld Key": "nw1750",
}
CAT = {  # picker column -> our category id (chest categories + base rewards)
    "Stones": "stones", "Juice": "juice", "Fusions": "fusions", "Leapstones": "leap",
    "Gold": "gold", "Free taps": "taps", "Bracelets": "brace", "Karma": "karma",
    "Selectable Astrogems": "astro", "Elysian ticket": "elysian", "Engraving kits": "kits",
    "Engraving books": "books", "Cards": "cards", "Gems": "gems",
    "Base shards": "b_shards", "Base red stones": "b_red", "Base blue stones": "b_blue",
    "Base leapstones": "b_leap",
}
def parse(v):   # "u|r|e" astrogem counts -> [uncommon, rare, epic]
    if isinstance(v, str) and "|" in v:
        return [float(x) for x in v.split("|")]
    return v
out = {"source": d["source_url"], "extracted_at": d["extracted_at"], "keys": {}}
for t in d["key_tiers"]:
    if t["label"] not in WANT: continue
    kid = WANT[t["label"]]
    cols = [c for c in t["columns"] if c in CAT]
    bands = []
    for f in t["floors"]:
        rw = {CAT[c]: parse(f["rewards"][c]) for c in cols if c in f["rewards"]}
        bands.append({"range": f["range"], "rewards": rw})
    chest_cats = [CAT[c] for c in cols if not c.startswith("Base")]
    out["keys"][kid] = {"label": t["label"], "element": t["element"],
                        "chest_cats": chest_cats, "bands": bands}
    print(kid, chest_cats, [len([c for c in b["rewards"] if c in chest_cats]) for b in bands])
json.dump(out, open("data/rewards.json", "w"), indent=1)
with open("data.js", "w") as f:
    f.write("// generated by tools/build_data.py from the reward-picker __DATA__ dump; do not hand-edit\n")
    f.write("const REWARDS=" + json.dumps(out, separators=(",", ":")) + ";\n")
print("ok")
